### ISSUE TITLE
Bug Ubuntu 22.04

### ISSUE THREAD

**Issue by GabrielOliveira23** [chon-group/velluscinum#10]
Foi instalado o pacote para jacamo como descrito no [Velluscinum JaCaMo Hello](https://github.com/chon-group/Velluscinum/wiki/Velluscinum-JaCaMo-Hello), com a versão do java 17, testado no Ubuntu 22.04 e wsl no windows (subsistema Ubuntu).
Vale ressaltar que quando testado o jacamo está funcionando corretamente, porém quando adicionado o pacote do velluscinum, o bug acontece.

O bug ocorre quando tenta-se executar o jcm:
```
jacamo helloVelluscinum.jcm
```

![image](https://github.com/user-attachments/assets/c74c838a-1eac-41b3-9a25-2542bb525c68)

**Comment by nilsonLazarin** [comment]
Olá @Ninjaalpha01,

Por hora, altere o arquivo build.gradle, para usar uma versão anterior do repositório do jacamo

- Onde: ___maven { url "https://raw.githubusercontent.com/jacamo-lang/mvn-repo/master" }___

- Mude para: ___maven { url "https://raw.githubusercontent.com/jacamo-lang/mvn-repo/69e273bcc8db980bbc9b0610dccfc3e5475f9794" }___

![image](https://github.com/user-attachments/assets/5430de08-5464-4aa6-b778-77ea2195bc0f)

Terei que subir as versões para JAVA 21, conforme orientação do Prof. Jomi https://github.com/jacamo-lang/mvn-repo/issues/2

**Comment by nilsonLazarin** [comment]
@Ninjaalpha01,
Nova versão do Jacamo-CLI disponível!!!
Para atualizar, siga as instruções em https://github.com/chon-group/dpkg-jacamo/releases/tag/jacamocli-v1.2-20241014
