### ISSUE TITLE
Nova Função loadWallet e saveWallet

### ISSUE THREAD

**Issue by GabrielOliveira23** [chon-group/velluscinum#5]
Criar uma função para carregar uma carteira digital já existente (loadWallet) e uma para salvar a carteira digital que deseja (saveWallet).
Com a existência destas funções seria possível o mesmo SMA ter suas propriedades salvas e carregadas em outras execuções dele mesmo, assim trazendo um cenário mais real e abrindo leque para cenários novos de aplicação do Velluscinum

**Comment by nilsonLazarin** [comment]
Recurso implementado @Ninjaalpha01, obrigado pela sugestão.

Na primeira execução, caso não existam os arquivos com as chaves do agente, ele executa o builWallet e o storeWallet

![primeira-execucao](https://github.com/chon-group/velluscinum/assets/32855001/45ff1d16-df99-4f8f-96d3-1d335d963b2d)

Nas próximas execuções ele já carrega as chaves do agente...

![segunda-execucao](https://github.com/chon-group/velluscinum/assets/32855001/4555bcc1-9aa6-4d53-8226-a51c7b2b9aea)
