### ISSUE TITLE
 Allow direct use of public and private keys without requiring text files

### ISSUE THREAD

**Issue by PedroOrPeter** [chon-group/velluscinum#9]
Currently, to pass the parameters for the public and private keys to Velluscinum, it is necessary to provide text files. I would like to suggest an enhancement that allows the direct input of keys, without the need for files.

Benefits:
    • Simplifies integration with systems that already have keys stored in variables or databases.
    • Reduces the need for file handling, making the process more efficient and straightforward.

**Comment by nilsonLazarin** [comment]
@PedroOrPeter 

Please execute in a terminal the command below to get the latest version.

``
sudo apt update; sudo apt install velluscinum-cli
``
